services:
  scraper:
    build: .
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017
    networks:
      - net

  mongo:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - net

networks:
  net:
    driver: bridge
